apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-view
subjects:
- kind: User
  name: {{ .Release.Name }}
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-node-reader
subjects:
- kind: User
  name: {{ .Release.Name }}
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-node-reader
  apiGroup: ""
