apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.version | default .Chart.AppVersion}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.version | default .Chart.AppVersion}}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      clusterRoleName: {{ .Values.clusterRole.name }}
      volumes:
      - name: dev-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice
      {{- if eq .Values.platform "eks"}}
      - name: breeze-data
        emptyDir: {}
      initContainers:
      - name: {{ .Release.Name }}-init
        image: {{ .Values.containerRegistryHostname }}/breeze-agent-init:latest
        imagePullPolicy: Always
        args: ["get-node-tags.py"]
        volumeMounts:
        - name: breeze-data
          mountPath: /breeze-data
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.containerRegistryHostname }}/breeze-agent:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        volumeMounts:
        - name: dev-tun
          mountPath: /dev/net/tun
        {{- if eq .Values.platform "eks"}}
        - name: breeze-data
          mountPath: /breeze-data
        {{- end }}
        env:
          - name: BREEZE_RUNTIME
            value: kubernetes
          - name: BREEZE_K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: BREEZE_K8S_TUNHUB_CLIENT
            value: enabled
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN"]
        readinessProbe:
          exec:
            command:
            - grep
            - zcat
            - "/proc/net/dev"
          initialDelaySeconds: 900
          periodSeconds: 60
          failureThreshold: 60
      imagePullSecrets:
      - name: {{ .Values.containerRegistrySecretsName }}
